name: hindi_audio_dataset
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - numpy
  - pandas
  - librosa
  - pydub
  - ffmpeg-python
  - gradio>=4.44.0
  - huggingface_hub==0.19.4
  - soundfile
  - pip:
      - webrtcvad-wheels>=2.0.14
